title: Nothing But Fun
description: A bunch of fun seekers in the Greater Pensacola area
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
github:
  show_downloads: false
  is_project_page: false
show_downloads: false
  
